version: '3.3'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root_pwd
      - PG_DATA=/var/lib/postgresql/data/pgdata/
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - db-data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:6.5.0
    restart: always
    environment:
      - discovery.type=single-node
      - cluster.name=LiferayElasticsearchCluster
      - xpack.security.enabled=false
      - network.bind_host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
  liferay:
    image: ibaiborodine/liferay-portal-ce:7.1.3-ga4-jdk11
    restart: always
    environment:
      LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED: "false"
      LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED: "false"
      LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED: "false"
      LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED: "false"
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "80:8080"
      - "11311:11311"
    volumes:
      - ./mnt/liferay/base:/etc/opt/liferay
      - /mnt/liferay/properties:/opt/liferay/tomcat/webapps/ROOT/WEB-INF/classes
      - lr-data:/opt/liferay/data/document_library

volumes:
  db-data:
  es-data:
  lr-data: